### ISSUE TITLE
The mIoU is very low when I tried the pre-trained model.

### ISSUE THREAD

**Issue by Siyuluan** [ifnspaml/PerfPredRec#2]
Hi,

Thank you so much for your code and pre-trained model! Your code helped me a lot.

I tried to use your code and pre-trained model to do segmentation task, but I found the mIoU is very low (0.2706 %, I use attacks.sh and set epsilon=0, and my dataset is cityscapes). 

I have three question, can you help me? 

When I run the swiftnet.sh to train a segmentation DNN, I met a bug, IndexError: Target 21 is out of bounds.  I think this is because of criterion_loss = self.criterion(preds, targets), I want to know is,

1. In your code, you use keys_to_load = ['color', 'segmentation_trainid'] in the train_swiftnet.py, why is ['color', 'segmentation_trainid'] not ['color', 'segmentation']? 

2. How did you get the segmentation_trainid folder? [IFN_Dataloader](https://github.com/ifnspaml/IFN_Dataloader) didn't say how to make a segmentation_trainid folder for the cityscapes dataset.

3 If I only have [gtFine] and [leftImg8bit] two folders under cityscapes folder, what I should change in the code so that I can use your pre-trained models?

Thanks in advance,

**Comment by AndrBaer** [comment]
Hi Siyu,

my

**Comment by AndrBaer** [comment]
Hi Siyu,

my guess for the low mIoU using attacks.sh would be that the labels are loaded in the wrong format. You could, however, try out to use the keys_to_load = ['color', 'segmentation'] (line 66) and labels_mode = 'fromid' (line 72) instead. With this configuration you load the Cityscapes original label format with 30+ classes and transform the labels into a smaller set of 19 classes as usually done for Cityscapes. The down side of this approach is the inference time due to transforming the labels on the fly from the 30+ class format to the 19 class format. Let me know, if you achieve a higher mIoU with this quick fix.

To your questions:
1. lines 76 and 97 of the dataloader use the argument labels_mode='fromtrainid' which is why you need to use keys_to_load = ['color', 'segmentation_trainid'], otherwise you load labels with the wrong format. The argument labels_mode indicates in what format the labels are loaded. In this particular case, you (should) load labels which already follow the trainid format (only 19 classes, see also lines 108-145 inhttps://github.com/ifnspaml/IFN_Dataloader/blob/master/dataloader/definitions/labels_file.py for the distinguishing between trainid and id label format). If you don't have trainid labels at hand, you could also use keys_to_load = ['color', 'segmentation'] combined with labels_mode='fromid'. This should work, but will slow down training as stated above.
2. Please check out https://github.com/ifnspaml/IFN_Dataloader/tree/master/dataloader/file_io for generating trainid labels yourself. You need to run https://github.com/ifnspaml/IFN_Dataloader/blob/master/dataloader/file_io/trainid_converter.py which also contains an example for Cityscapes in lines 402-414.
3. If you only have gtFine and leftImg8bit at hand and don't necessarily want to use segmentation_trainid, you only need the json files of the dataset (see also here https://github.com/ifnspaml/AdvAttackDet) and use keys_to_load = ['color', 'segmentation'] and labels_mode='fromid'.
